config/routes.rb
Rails.application.routes.draw do

  match "/email_to_friend/:type/:id" => 'email_sender#send_mail', :as => :email_to_friend

  namespace :admin do
    resource :captcha_settings
  end

end

app/models/captcha_configuration.rb
class CaptchaConfiguration < Configuration
  THEMES = ['red', 'white', 'blackglass', 'clean', 'custom']

  # this keys works for localhost
  preference :private_key, :string, :default => '6LfIsgEAAAAAAGfB6Z0lEUtdL3GVuBkRa9cYlMZz'
  preference :public_key, :string, :default => '6LfIsgEAAAAAALpT20eiC3RslZQmmCbiNS-AUvSe'
  preference :theme, :string, :default => 'red'
  preference :use_captcha, :boolean, :default => true
end

app/models/mail_to_friend.rb
class MailToFriend
  include ActiveModel::Validations
  include ActiveModel::Conversion
  attr_accessor :host, :subject, :sender_name, :sender_email, :recipient_name, :recipient_email, :message, :recipients, :invalid_recipients, :hide_recipients

  EMAILREGEX = /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,8}$/i

  validates :subject, :presence => true
  validates :sender_name, :presence => true
  validates :recipient_name, :presence => true, :unless => :is_multi
  validates :sender_email, :format => { :with => EMAILREGEX }
  validates :recipients, :length => {:minimum => 1, :message => "must contain at least one valid email address"}
  validates :invalid_recipients, :length => {:maximum => 0, :message => "must be removed"}

  def initialize(opts = {})
    @subject      = opts[:subject]      || I18n.t('email_to_friend.you_would_like_this')
    @sender_email = opts[:sender_email] || ' '
    @sender_name  = opts[:sender_name]  || @sender_email.split('@', 2)[0].titleize

    @recipients = []
    @invalid_recipients = []

    @recipient_email = (opts[:recipient_email] || '').gsub(';', ',').gsub(/\s/ , '')
    @recipient_email.split(',').each do |address|
      if address =~ EMAILREGEX
         @recipients << address
      else
        @invalid_recipients << address
      end
    end

    @recipient_name = opts[:recipient_name]
    @recipient_name ||= @recipients[0].split('@', 2)[0].titleize unless @recipients.empty?

    @hide_recipients = opts[:hide_recipients] || false
    @message = opts[:message]
  end

  def persisted?
    false
  end

  def is_multi
    (@recipients.size + @invalid_recipients.size) > 1
  end
end

app/controllers/admin/captcha_settings_controller.rb
#~ class Admin::CaptchaSettingsController < Admin::BaseController
  #~ def update
    #~ Spree::Captcha::Config.set(params[:preferences])

    #~ respond_to do |format|
      #~ format.html {
        #~ redirect_to admin_captcha_settings_path
      #~ }
    #~ end
  #~ end
#~ end

#new

class Admin::CaptchaSettingsController < Admin::BaseController
  def update

		config=Configuration.find_by_name("Captcha configuration")
    domain=get_sub_domain(current_subdomain)
    preference_checking=Preference.where("domain_url=? AND owner_type=? AND owner_id=?",domain,"Configuration",config.id)	
  	if preference_checking.blank?
    preference=Preference.create(:name=>"public_key",:owner_id=>config.id,:owner_type=>"Configuration",:value=>params[:preferences][:public_key],:domain_url=>domain)
    preference=Preference.create(:name=>"theme",:owner_id=>config.id,:owner_type=>"Configuration",:value=>params[:preferences][:theme],:domain_url=>domain)
		preference=Preference.create(:name=>"private_key",:owner_id=>config.id,:owner_type=>"Configuration",:value=>params[:preferences][:private_key],:domain_url=>domain)
   else
    preference_checking.each do |preference|
      preference.value= params[:preferences][:public_key] if preference.name=="public_key"
      preference.value= params[:preferences][:theme] if preference.name=="theme"
		  preference.value= params[:preferences][:private_key] if preference.name=="private_key"
      preference.save
    end
    end
    respond_to do |format|
      format.html {
        redirect_to admin_captcha_settings_path
      }
    end
  end
end

app/controllers/email_sender_controller.rb
class EmailSenderController < Spree::BaseController
  before_filter :find_object
include Spree::BaseHelper
  def send_mail
    if request.get?
      @mail_to_friend = MailToFriend.new(:sender_email => current_user.try(:email))
    else
      mail_to_friend
    end
  end

  private

  def mail_to_friend
  @mail_to_friend = MailToFriend.new(params[:mail_to_friend])
   @mail_to_friend.host = request.env["HTTP_HOST"]
    respond_to do |format|
      format.html do
        preferences=find_domain_preference("Captcha configuration")
        captcha_passed = verify_recaptcha(:private_key => preferences.select{|x|x.name=="private_key"}.map(&:value))
        if @mail_to_friend.valid? && captcha_passed
          flash[:notice] = I18n.t('email_to_friend.mail_sent_to', :email => @mail_to_friend.recipient_email).html_safe
          flash[:notice] << ActionController::Base.helpers.link_to(I18n.t('email_to_friend.send_to_other'), email_to_friend_path(@object.class.name.downcase, @object)).html_safe
         send_message(@object, @mail_to_friend)
          method_name = "after_delivering_#{@object.class.name.downcase}_mail"
          send(method_name) if respond_to?(method_name, true)
          redirect_to @object
        else
          flash[:error]="Enter recaptcha correctly"
          render "send_mail"
        end
      end
    end
  end

  #extract send message to make easier to override
  def send_message(object, mail_to_friend)
    ToFriendMailer.deliver_mail_to_friend(object,@mail_to_friend)
  end

  def find_object
    class_name = params[:type].titleize.constantize
    return false if params[:id].blank?
    @object = class_name.find_by_id(params[:id])
    if class_name.respond_to?('find_by_permalink')
      @object ||= class_name.find_by_permalink(params[:id])
    end
    if class_name.respond_to?('get_by_param')
      @object ||= class_name.get_by_param(params[:id])
    end
  end

end

app/views/admin/captcha_settings/edit.html.erb
<%= render  'admin/shared/configuration_menu' %>

<h1><%= t("captcha.captcha_settings") %></h1>

<% form_tag(admin_captcha_settings_path, :method => :put) do -%>
  <p>
	  <%preferences=find_domain_preference("Captcha configuration")%>

<% unless preferences.present?%>


    <label><%= t("captcha.public_key") %>:</label>
    <%= text_field_tag('preferences[public_key]',"Specify your public key", :size => 40) %>
  </p>
  <p>
    <label><%= t('captcha.private_key') %>:</label>
    <%= text_field_tag('preferences[private_key]',"Specify your private key", :size => 40)%>
  </p>
  <p>
    <label><%= t('captcha.theme') %>:</label>
    <%= select_tag('preferences[theme]', options_for_select(CaptchaConfiguration::THEMES, Spree::Captcha::Config[:theme])) %>
  </p>
  
	<%else%>
	
  <%preferences.each do |preference|%>
 <% if preference.name=="public_key"%>
 <p>
  <label><%= t("captcha.public_key") %>:</label>
    <%= text_field_tag('preferences[public_key]', preference.value, :size => 40) %>
  </p>
	  <%elsif preference.name=="private_key" %>
		<p>
		 <label><%= t('captcha.private_key') %>:</label>
    <%= text_field_tag('preferences[private_key]', preference.value, :size => 40)%>
		</p>
			  <%elsif preference.name=="theme" %>
  <p>
    <label><%= t('captcha.theme') %>:</label>
    <%= select_tag('preferences[theme]', options_for_select(CaptchaConfiguration::THEMES, Spree::Captcha::Config[:theme])) %>
  </p>
		<%end%>
		<% end -%>
	<%end%>
  <p class="form-buttons">
    <%= button t('update') %>
    <%= t("or") %> <%= link_to t("cancel"), admin_captcha_settings_url %>
  </p>
	<%end%>

app/views/admin/captcha_settings/show.html.erb
<%= render 'admin/shared/configuration_menu' %>

<h1><%= t("captcha.captcha_settings") %></h1>
	  <%preferences=find_domain_preference("Captcha configuration")%>
    <% unless preferences.present?  %>
<table>
  <tr>
    <th scope="row"><%= t("captcha.public_key") %>:</th>
    <td>Not available</td>
  </tr>
  <tr>
    <th scope="row"><%= t("captcha.private_key") %>:</th>
    <td>Not available</td>
  </tr>
  <tr>
    <th scope="row"><%= t("captcha.theme") %>:</th>
    <td>Not Available</td>
  </tr>
</table>

<p>
  <%= link_to_with_icon('edit', t("edit"), edit_admin_captcha_settings_path) %>
</p>
<%else%>
<table>
<%preferences.each do |preference|%>
<% if preference.name=="public_key"%>
 <tr>
    <th scope="row"><%= t("captcha.public_key") %>:</th>
    <td><%= preference.value %></td>
  </tr>
	<% elsif preference.name=="private_key"%>
	 <tr>
    <th scope="row"><%= t("captcha.private_key") %>:</th>
    <td><%=preference.value%></td>
  </tr>
		<% elsif preference.name=="theme"%>
	<tr>
    <th scope="row"><%= t("captcha.theme") %>:</th>
    <td><%= preference.value%></td>
  </tr>
<%end%>
<%end%>
<table>
<p>
  <%= link_to_with_icon('edit', t("edit"), edit_admin_captcha_settings_path) %>
</p>
<%end%>

app/views/email_sender/send_mail.html.erb
<h1><%= t('email_to_friend.tell_about', :product => @object.name) %></h1>

<%= form_for(@mail_to_friend, :url => "") do |f| -%>
  <%= render "shared/error_messages", :target => @mail_to_friend %>
  <%= hook :send_mail_fields, {:f => f} do %>
  <p>
    <%= f.label(:sender_name, t('email_to_friend.sender_name')) %><br/>
    <%= f.text_field(:sender_name) %>
  </p>
  <p>
    <%= f.label(:sender_email, t('email_to_friend.sender_email')) %><br/>
    <%= f.text_field(:sender_email) %>
  </p>
  <p>
    <%= f.label(:recipient_name, t('email_to_friend.recipient_name')) %><br/>
    <%= f.text_field(:recipient_name) %>
  </p>
  <p>
    <%= f.label(:recipient_email, t('email_to_friend.recipient_email')) %><br/>
    <%= f.text_field(:recipient_email) %>
  </p>
  <p>
    <%= f.label(:message, t('email_to_friend.message')) %><br/>
    <%= f.text_area(:message) %>
  </p>
  <% end %>
	<%preferences=find_domain_preference("Captcha configuration")%>
 <%if preferences && preferences.blank?%>
 
    <%= recaptcha_tags :public_key => Spree::Captcha::Config[:public_key], :display => {:theme => Spree::Captcha::Config[:theme]} %>
	<%else%>
	    <%= recaptcha_tags :public_key =>preferences.select{|x|x.name=="public_key"}.map(&:value), :display => {:theme =>preferences.select{|x|x.name=="public_key"}.map(&:value) }%>

	<%end%>  

  <p>
    <%= f.submit(t('email_to_friend.send_message')) %>
  </p>
<% end -%>

app/views/products/_mail_to_friend.html.erb
<%= mail.recipient_name %>,

I think you would like this item:

  * <%= product.name %>

<% unless mail.message.blank? -%>
<%= mail.message %>
<% end -%>

<%= mail.sender_name %>

Click the link below to view the <%= product.name %> page.
<%= product_url(product) %>

For more online shopping, visit <%= products_url %>